name: Build Alpine CI images

on:
  workflow_call:
    inputs:
      alpine_version:
        description: Alpine minirootfs version
        required: true
        type: string

permissions:
  contents: read
  packages: write

concurrency:
  group: alpine-images-${{ github.ref }}
  cancel-in-progress: true

jobs:
  target:
    name: Build target ${{ matrix.target }}

    strategy:
      fail-fast: false
      matrix:
        target:
          - gnu
          - llvm

    uses: ./.github/workflows/alpine-image-target.yml
    with:
      target: ${{ matrix.target }}
      alpine_version: ${{ inputs.alpine_version }}