name: Continuous Integration
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Refresh dependencies
        run: sudo apt update
      - name: Install dependencies
        run: sudo apt install shellcheck -y
      - name: Run pre-commit hooks
        run: |
          ./contrib/setup
          source venv/bin/activate
          sed -i "/no-commit-to-branch/,+1d" .pre-commit-config.yaml
          pre-commit run --all-files

  alpine-build:
    uses: ./.github/workflows/alpine-build.yml
    secrets: inherit

  fwupd-build:
    uses: ./.github/workflows/fwupd-build.yml
    secrets: inherit

  ubuntu-legacy-build:
    uses: ./.github/workflows/ubuntu-legacy-build.yml
    secrets: inherit
